CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    name VARCHAR(50) NOT NULL,
    avatar_url VARCHAR(500),
    total_steps BIGINT NOT NULL DEFAULT 0,
    current_city_id VARCHAR(50),
    kakao_id BIGINT UNIQUE,
    google_id VARCHAR(255) UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_kakao ON users (kakao_id);
CREATE INDEX idx_users_google ON users (google_id);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(500) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rt_token ON refresh_tokens (token);
CREATE INDEX idx_rt_user ON refresh_tokens (user_id);

CREATE TABLE user_currency (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    coupons INTEGER NOT NULL DEFAULT 0,
    hearts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE currency_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    currency_type VARCHAR(20) NOT NULL CHECK (currency_type IN ('coupon', 'heart')),
    amount INTEGER NOT NULL,
    reason VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ct_user ON currency_transactions (user_id);
CREATE INDEX idx_ct_user_created ON currency_transactions (user_id, created_at DESC);

CREATE TABLE cities (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    country_flag VARCHAR(10),
    steps_required BIGINT NOT NULL DEFAULT 0,
    lat NUMERIC(10, 6),
    lng NUMERIC(10, 6),
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE city_foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id VARCHAR(50) NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    UNIQUE (city_id, name)
);

CREATE TABLE city_landmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id VARCHAR(50) NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    UNIQUE (city_id, name)
);

CREATE TABLE missions (
    id VARCHAR(50) PRIMARY KEY,
    city_id VARCHAR(50) NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('photo', 'food', 'writing', 'explore', 'social')),
    title VARCHAR(200) NOT NULL,
    description TEXT,
    image_url VARCHAR(500),
    steps_required BIGINT NOT NULL DEFAULT 0,
    emoji VARCHAR(10),
    reward VARCHAR(200),
    ai_composite BOOLEAN NOT NULL DEFAULT FALSE,
    ai_prompt TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_missions_city ON missions (city_id);

CREATE TABLE user_missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mission_id VARCHAR(50) NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'locked' CHECK (status IN ('locked', 'available', 'completed')),
    completed_at TIMESTAMP NULL,
    composite_image_url VARCHAR(500),
    UNIQUE (user_id, mission_id)
);

CREATE INDEX idx_um_user ON user_missions (user_id);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    city_id VARCHAR(50) NOT NULL REFERENCES cities(id),
    content TEXT NOT NULL,
    image_key VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_posts_user ON posts (user_id);
CREATE INDEX idx_posts_city ON posts (city_id);
CREATE INDEX idx_posts_created ON posts (created_at DESC, id DESC);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_comments_post ON comments (post_id, created_at ASC);

CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, user_id)
);

CREATE INDEX idx_likes_post ON likes (post_id);

CREATE TABLE friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    method VARCHAR(20) NOT NULL CHECK (method IN ('same_city', 'different_city', 'qr')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, friend_id)
);

CREATE INDEX idx_friendships_user ON friendships (user_id);

CREATE TABLE step_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    steps BIGINT NOT NULL,
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ssl_user ON step_sync_log (user_id);
CREATE INDEX idx_ssl_user_date ON step_sync_log (user_id, synced_at);

CREATE TABLE user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mission_id VARCHAR(50) NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
    city_id VARCHAR(50) NOT NULL REFERENCES cities(id),
    title VARCHAR(200) NOT NULL,
    emoji VARCHAR(10),
    earned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, mission_id)
);

CREATE INDEX idx_ub_user ON user_badges (user_id);

CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user2_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    last_message TEXT,
    last_message_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user1_id, user2_id)
);

CREATE INDEX idx_cr_user1 ON chat_rooms (user1_id);
CREATE INDEX idx_cr_user2 ON chat_rooms (user2_id);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cm_room_created ON chat_messages (room_id, created_at ASC);
