ALTER TABLE user_currency
    ADD COLUMN tickets INTEGER NOT NULL DEFAULT 0;

ALTER TABLE currency_transactions
    DROP CONSTRAINT IF EXISTS currency_transactions_currency_type_check;

ALTER TABLE currency_transactions
    ADD CONSTRAINT currency_transactions_currency_type_check
    CHECK (currency_type IN ('coupon', 'heart', 'ticket'));

CREATE TABLE walk_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_date DATE NOT NULL,
    activity_type VARCHAR(20) NOT NULL CHECK (activity_type IN ('walk', 'run')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'abandoned')),
    city_id VARCHAR(50) NOT NULL REFERENCES cities(id),
    goal_meters INTEGER NOT NULL DEFAULT 1000,
    distance_meters INTEGER NOT NULL DEFAULT 0,
    bonus_meters INTEGER NOT NULL DEFAULT 0,
    duration_seconds INTEGER NOT NULL DEFAULT 0,
    tickets_earned INTEGER NOT NULL DEFAULT 0,
    stamps_earned INTEGER NOT NULL DEFAULT 0,
    environment_hint VARCHAR(100),
    playlist_title VARCHAR(100),
    playlist_url VARCHAR(500),
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, session_date)
);

CREATE INDEX idx_walk_sessions_user_date ON walk_sessions (user_id, session_date DESC);
CREATE INDEX idx_walk_sessions_user_status ON walk_sessions (user_id, status);

CREATE TABLE walk_session_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES walk_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitude NUMERIC(10, 6) NOT NULL,
    longitude NUMERIC(10, 6) NOT NULL,
    accuracy_meters NUMERIC(8, 2),
    distance_from_previous_meters INTEGER NOT NULL DEFAULT 0,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_wsl_session_recorded ON walk_session_locations (session_id, recorded_at ASC, id ASC);
CREATE INDEX idx_wsl_user_recorded ON walk_session_locations (user_id, recorded_at DESC);

CREATE TABLE walk_session_missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES walk_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mission_key VARCHAR(80) NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT,
    proof_type VARCHAR(20) NOT NULL CHECK (proof_type IN ('photo', 'text', 'session', 'screenshot', 'social')),
    emoji VARCHAR(10),
    bonus_meters INTEGER NOT NULL DEFAULT 100,
    stamp_reward VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'completed')),
    verification_status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (verification_status IN ('pending', 'verified', 'rejected', 'fallback_accepted')),
    image_key VARCHAR(500),
    text_proof TEXT,
    completed_at TIMESTAMP NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (session_id, mission_key)
);

CREATE INDEX idx_wsm_session ON walk_session_missions (session_id, sort_order ASC);
CREATE INDEX idx_wsm_user ON walk_session_missions (user_id, created_at DESC);

CREATE TABLE mission_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES walk_sessions(id) ON DELETE CASCADE,
    session_mission_id BIGINT NOT NULL REFERENCES walk_session_missions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    city_id VARCHAR(50) NOT NULL REFERENCES cities(id),
    title VARCHAR(160) NOT NULL,
    content TEXT,
    image_key VARCHAR(500),
    visibility VARCHAR(20) NOT NULL DEFAULT 'friends' CHECK (visibility IN ('friends')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mission_stories_user_created ON mission_stories (user_id, created_at DESC, id DESC);
CREATE INDEX idx_mission_stories_city_created ON mission_stories (city_id, created_at DESC, id DESC);
